# Generated by Django 2.1.3 on 2018-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libapi.PublicationHouse'),
        ),
    ]
